services:
  mosquitto:
    image: eclipse-mosquitto:1.6.15
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: always
    networks:
      - my_network

  ignition:
    image: inductiveautomation/ignition:latest
    container_name: ignition
    ports:
      - "8088:8088"
    restart: always
    networks:
      - my_network


  iot-simulator:
    build:
      context: .
    container_name: iot-simulator
    depends_on:
      - mosquitto
    networks:
      - my_network

networks:
  my_network:
    driver: bridge