services:
  mosquitto:
    image: eclipse-mosquitto:1.6.15
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: always


  ignition:
    image: inductiveautomation/ignition:latest
    container_name: ignition
    ports:
      - "8088:8088"
    restart: always



  iot-simulator:
    build:
      context: .
    container_name: iot-simulator
    depends_on:
      - mosquitto

  postgres_db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin  
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pg_database
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
volumes:
  postgres_data: